server: 
  port: 9527
 
spring: 
  application:
    name: servicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
 
zuul: 
  ignored-services: "*"                     #原真实服务名忽略，单个具体，多个可以用"*"
  prefix: /guet                             #设置统一公共前缀
  routes: 
    dept.serviceId: servicecloud-dept
    dept.path: /**

 
info:
  app.name: guet-microservicecloud
  company.name: www.guet.edu.com
  build.artifactId: servicecloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT

