server: 
  port: 3344 
  
spring:
  application:
    name:  servicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ljw616/servicecloud-config.git #GitHub上面的git仓库名字  git@github.com:ljw616/servicecloud-config.git     https://github.com/ljw616/servicecloud-config.git
 

